##################################################################
#----------__----------------_ __--__------------------------ __ #
#-- ____ _/ /___ ___________(_) /_/ /___--__ __--______ ___--/ / #
#--/ __ `/ / __ `/ ___/ ___/ / __/ __/ / / // / / / __ `__ \/ /--#
# / /_/ / / /_/ / /__/ /--/ / /_/ /_/ /_/ // /_/ / / / / / / /---#
# \__,_/_/\__,_/\___/_/--/_/\__/\__/\__, (_)__, /_/ /_/ /_/_/----#
#----------------------------------/____/ /____/-----------------#
#-----------------  "...the fastest terminal ever!"  ------------#
#-----------------                      -- the devs  ------------#
##################################################################
# * Alacritty wiki: https://github.com/alacritty/alacritty/wiki  #
# * My dotfiles:    https://github.com/lamekino/dotfiles         #
##################################################################
# Appearance {{{
#background_opacity: 0.95
color-schemes:
  gruvbox-dark: &gruvbox-dark
    primary:
      background: '#1c1c1c'
      foreground: '#ebdbb2'
    cursor:
      cursor:     '#ebdbb2'
      text:       '#1c1c1c'
    normal:
      black:      '#282828'
      red:        '#cc241d'
      green:      '#98971a'
      yellow:     '#d79921'
      blue:       '#458588'
      magenta:    '#b16286'
      cyan:       '#689d6a'
      white:      '#a89984'
    bright:
      black:      '#928374'
      red:        '#fb4934'
      green:      '#b8bb26'
      yellow:     '#fabd2f'
      blue:       '#83a598'
      magenta:    '#d3869b'
      cyan:       '#8ec07c'
      white:      '#ebdbb2'
    selection:
      background: '#83a598'
      text:       '#ebdbb2'

  jellybeans: &jellybeans
    primary:
      background: '#121212'
      foreground: '#e4e4e4'
    cursor:
      cursor:     '#a97ca4'
      text:       '#feffff'
    selection:
      background: '#a97ca4'
      text:       '#feffff'
    normal:
      black:      '#393939'
      red:        '#ca674a'
      green:      '#96a967'
      yellow:     '#d3a94a'
      blue:       '#5778c1'
      magenta:    '#9c35ac'
      cyan:       '#6eb5f3'
      white:      '#a9a9a9'
    bright:
      black:      '#535551'
      red:        '#ea2828'
      green:      '#87dd32'
      yellow:     '#f7e44d'
      blue:       '#6f9bca'
      magenta:    '#a97ca4'
      cyan:       '#32dddd'
      white:      '#e9e9e7'

colors: *jellybeans
# }}}
# Fonts {{{
fonts:
  ibm-plex: &plex-medium
    size: 12.0
    normal:
      family: IBM Plex Mono Medium
      style:  Regular
    bold:
      family: IBM Plex Mono
      style:  Bold
    italic:
      family: IBM Plex Mono Medium
      style:  Italic
    bold_italic:
      family: IBM Plex Mono
      style:  Bold Italic
    offset:
        x: -1
        y: -2
    glyph_offset:
      x: 0
      y: 0
font: *plex-medium
# }}}
# Terminal Settings {{{
dynamic_title: false
live_config_reload: true

env:
  TERM: xterm-256color

window:
  title: Alacritty
  padding:
    x: 4
    y: 4
  decorations: none
  # startup_mode: Maximized

scrolling:
  history: 8192

cursor:
  style: Block
  unfocused_hollow: true

selection:
  save_to_clipboard: false
# }}}
# Mouse/keyboard {{{
mouse:
  hide_when_typing: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
# }}}
