# background_opacity: 0.95
dynamic_title: false
live_config_reload: true

env:
  TERM: xterm-256color

window:
  title: Alacritty
  padding:
    x: 4
    y: 4
  decorations: none
  startup_mode: Maximized

scrolling:
  history: 0

cursor:
  style: Block
  unfocused_hollow: true

font:
  size: 12.0
  normal:
    family: IBM Plex Mono Medium
    style:  Regular
  bold:
    family: IBM Plex Mono Medium
    style:  Bold
  italic:
    family: IBM Plex Mono Medium
    style:  Medium Italic
  bold_italic:
    family: IBM Plex Mono Medium
    style:  Medium Bold Italic
  offset:
      x: -1
      y: -2
  glyph_offset:
    x: 0
    y: 0

colors:
  primary:
    foreground: '#ebdbb2'
    background: '#1c1c1c'
  cursor:
    cursor:     '#ebdbb2'

  normal:
    black:      '#282828'
    red:        '#cc241d'
    green:      '#98971a'
    yellow:     '#d79921'
    blue:       '#458588'
    magenta:    '#b16286'
    cyan:       '#689d6a'
    white:      '#a89984'
  bright:
    black:      '#928374'
    red:        '#fb4934'
    green:      '#b8bb26'
    yellow:     '#fabd2f'
    blue:       '#83a598'
    magenta:    '#d3869b'
    cyan:       '#8ec07c'
    white:      '#ebdbb2'

selection:
  save_to_clipboard: false

mouse:
  hide_when_typing: false

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
