alias grep='grep --color=auto'
alias lablk="lsblk -o name,label,size,ro,type,mountpoint,uuid"
alias ls='LC_ALL=C ls -pk --color=auto --group-directories-first'
alias ll='LC_ALL=C ls -pklh --color=auto --group-directories-first'
alias la='LC_ALL=C ls -pkah --color=auto --group-directories-first'
alias lla='LC_ALL=C ls -pkalh --color=auto --group-directories-first'
alias diff='diff --color=always'
alias feh='feh -x --scale-down'
alias open='xdg-open'
alias trash='gio trash'
